version: '3.8'

services:
  # Development service
  react-dev:
    container_name: react-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development

  # Production service
  react-prod:
    container_name: react-prod
    build:
      context: .
      target: production
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production